### ISSUE TITLE
guifi66 database inclusion

### ISSUE THREAD

**Issue by rgf1042** [guifi/docker-drupal-guifi#1]
When trying to include guifi66 development database inside working drupal database then apache shows an error and webpage seems to be out of service (404 ERROR).

/var/log/error.log files shows the next lines:
---------------
[Thu Jul 27 11:02:45.823225 2017] [:error] [pid 407] [client 172.19.0.1:57726] P
HP Notice:  Undefined variable: variables in /usr/share/drupal/guifi-web/include
s/bootstrap.inc on line 568
[Thu Jul 27 11:02:45.823767 2017] [:error] [pid 407] [client 172.19.0.1:57726] P
HP Notice:  Undefined variable: variables in /usr/share/drupal/guifi-web/include
s/bootstrap.inc on line 575
---------------

**Comment by miquelmartos** [comment]
Diria que estàs utilitzant una base de dades incompleta.
Descarrega novament la db devel.
El modul "budgets" et farà falta instal.lar-lo i activar-lo si o si.

**Comment by rgf1042** [comment]
Ostres doncs la base de dades l agafo de la web de guifi, potser no és aquest el link. Provaré d incloure ja el mòdul budgets i aviam si així se soluciona el problema. Moltes gràcies per l aportació.

**Comment by miquelmartos** [comment]
he regenerat el fitxer guifi66_devel.sql.gz, ho fa sol cada 15 dies, però segurament l'ultim dia que ho va fer hi havia alguna taula corrupta i no es va completar.
Ara si que hi ha una versió correcte.

**Comment by rgf1042** [comment]
Moltes gràcies Miquel, amb aquestes 2 modificacions l'entorn ja funciona, ara només em falta ficar el tema de guifi.
