### ISSUE TITLE
guifi2011 theme issues

### ISSUE THREAD

**Issue by rgf1042** [guifi/docker-drupal-guifi#5]
When enabling guifi2011 theme it needs to manually go to guifi2011 theme configure sub menu and save settings without doing anything else, explained here:
 (http://ca.wiki.guifi.net/wiki/Preparant_l'entorn_de_desenvolupament)

One possible solution could be debug (with xdebug) which code the server executes when save configuration is pressed and generate an script that automatizes this process.

**Comment by miquelmartos** [comment]
Realment això no es un bug, en un entorn de desenvolupament, si la primera vegada cal fer algun ajustament manual tampoc es massa problema, de totes maneres es pot resoldre.
El theme_guifinet2011 realment es el theme garland amb alguna pagina modificada.
El funcionament del theme garland, quan tries els colors i deses els canvis, això genera dinàmicament unes imatges amb els colors seleccionats i ho desa en una carpeta amb un nom aleatori cada vegada que es canvi algun valor. Aquest directori es pot consultar a la base de dades a la taula "variables" als camps:
color_guifi.net2011_logo, color_guifi.net2011_screenshot, color_guifi.net2011_stylesheets i color_guifi.net2011_files.
El dump per a la base de dades devel inclou aquestes variables amb el contingut actual, ara mateix, i des de almenys febrer de 2014 que no s'ha canviat el path es: files/color/guifi.net2011-673770f4

Si al instal.lador del docker forces que es crei aquesta carpeta amb els seus fitxers corresponents aleshores no farà falta anar al panell d'administració per a canviar generar nous colors.
He preparat un fitxer comprimit amb la carpeta i el seu contingut:
https://guifi.net/files/color/guifi.net2011-673770f4.tgz

Ara te aquest codi "673770f4" però si mai fem un canvi als colors a la web oficial (no previst) aquest valor canviarà. En tot cas es podria generar el dump devel sempre amb un valor concret.

**Comment by rgf1042** [comment]
Ho havia definit com a bug de la imatge docker perquè l objectiu d ella és que sigui totalment automàtic. Moltes gràcies per l aportació, de fet buscava un sistema de fer el que tu em proposes però no sabia del tot cert quins fitxers buscava el tema. Després al vespre intentaré fer-ho!

**Comment by rgf1042** [comment]
He provat tot el que m'has dit i funciona a la perfecció, tanco la issue. Merci!
