### ISSUE TITLE
missing google API key for maps

### ISSUE THREAD

**Issue by ghost** [guifi/docker-drupal-guifi#8]
as seen in SAX 2017, when you go to maps, an API key is required for google maps

**Comment by studi7** [comment]
Hi, I was reading the docs of get api key on google maps API and found this tip:
_During development and testing, you can register a project for testing purposes in the Google API Console and use a generic, unrestricted API key._ [read more](https://developers.google.com/maps/documentation/javascript/get-api-key)
I have tried a new unrestricted key into guifi-dev environtment and it works.

in the file sites/all/modules/guifi/guifi_includes.inc.php replace line 2163 by this:
`drupal_set_html_head('<script src="https://maps.google.com/maps/api/js?sensor=false&libraries=places&v=3.22&key=YOUR_API_KEY' .
`

**Comment by ghost** [comment]
Great @studi7 !

I would like to see you doing the pull request and committing on that :D

If you need help ask here or via chat.

You have to use perl search & replace regular expression in drupal-entry.pl

**Comment by rgf1042** [comment]
Great job! I'll try to make an script for replacing old api key with this you supplied.

**Comment by studi7** [comment]
Ok, I will try too. So I'll take my first steps in regex perl ;)

**Comment by rgf1042** [comment]
Perfect! :D I got an API From Google, now I'll replace manually the line for testing it.

**Comment by rgf1042** [comment]
Solved!
